token: TOKEN_HERE
bot:
  command_prefix: "&"
  debug_guilds:
    - 771477382409879602
  help_command: null
cogs:
  sysbot:
    ip: 192.168.0.1
    port: 6000
  commands:
    text:
      hello,hi: |
        Hello, {{ ctx.author.name }}! Server time: **{{ now.strftime('%-I:%M %p') }}**
      ping: |
        🏓️ Pong! Latency: {{ '%.2fms' | format(ctx.bot.latency * 1000) }}
      /goodmorning: |
        Good morning {{ ctx.author.mention }}!
        Current server time is **{{ now.strftime("%-I:%M %p") }}**, {{ weekdays[now.weekday()] }}
        Your luck today: {{ "%.1f/%d" | format(luck, max_luck) }}
      /goodnight: |
        It's {{ now.strftime('%-I %p') }}, good night {{ ctx.author.name }}!
      today: |
        Today is {{ now.strftime('%F') }}, {{ weekdays[now.weekday() ]}}
      time: |
        Current server time: {{ now.strftime('%T') }}
      /luck: |
        Your luck today: {{ "%.1f/%d" | format(luck, max_luck) }}
        Rating: {{ luck_rating }}
      /serverluck: |
        {% if server_luck %}
        Server luck today: {{ "%.1f/%d" | format(server_luck, max_luck) }}
        Rating: {{ server_luck_rating }}
        {% else %}
        This command will only work on a server!
        {% endif %}
    load_files:
      - "*.md"
  luck:
    mu: 80
    sigma: 9
    max_luck: 100
    rating_levels: [55,60,65,70,75,80,85,90,95,100]
    rating_stars: "★☆"
  variables:
    weekdays:
      - happy Monday!
      - have a great Tuesday!
      - have a great Wednesday!
      - have a fun Thursday!
      - happy Friday!
      - enjoy your Saturday!
      - enjoy your Sunday! Don't forget to buy turnips in the morning!
  announcement: {}
  admin:
    channels:
      - 797864915750355016
    vote_valid_seconds: 300
    vote_count_required: 3
    messages:
      lock: ':red_circle: **Channel locked.** This bot is offline, please use one of the other bots.'
      unlock: ':green_circle: **Channel unlocked.** This bot is now online and ready to use.'
  time:
    timezone: Europe/Berlin
